### ISSUE TITLE
Incorrect usage of real.lerp

### ISSUE THREAD

**Issue by Frotty** [eGlint/wurstNoiselib#2]
Hi, thanks for this lib. However I encountered weird issue when using it. 
This is because you are using real.lerp which is not a normal linear interpolation, see Interpolation.wurst
real.lerp is a modified lerp adopted from gdx.
![image](https://user-images.githubusercontent.com/1486037/113187291-f7606880-9258-11eb-99de-3e61efb49439.png)

Please add unit tests!

**Comment by Frotty** [comment]
To be honest even with this fix I can hardly get any good results.
Could you improve documentation with examples and perhaps the offset/scale/amplitude mechanics?

**Comment by eGlint** [comment]
I just updated wurstNoiselib to v1.1.0, solving the lerp issue. I don't know if the documentation I provided is clear enough. 

If you couldn't get any good results with Perlin Noise, you can try out using the 2D Open Simplex function I just added.

**Comment by Frotty** [comment]
Thanks, will check.

**Comment by Frotty** [comment]
@eGlint I finally figured out why all my results were bad... I did not call `generateRandomPermutation`.
Nowhere does it say to do this...😬 Please add to package header doc and usage example!
Is there any reason it is not called automatically in an init block? `p`should never be all zeroes I think.
Please fix this. Now my generation actually makes sense, thanks again for the lib.

**Comment by eGlint** [comment]
Well, the reason why I did not put  `generateRandomPermutation` in the init block is because I assume there is a possibility the initialization of the other libraries that uses the noise functions might run first before the initialization of this library. Having the possibility of the permutation table still uninitialized. I expected those who will use this library can fix the issue by manually calling `generateRandomPermutation` in the init block of their own library. 

The lack of documentation and my flawed implementation of this library is causing the issue. In the next update, I'll make sure this inconvenience you experienced won't happen again. Thanks for your feedback!

**Comment by Frotty** [comment]
You could still have it in init block by default though 😕 
If there are issues, you can offer `generateRandomPermutation` as an option to use imho.
Anyway closing the issue.
